
version: '3.8'

services:

  client-backend:
    container_name: client-back-1
    image: client:0.0.1
    build:
#      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres

  service-db:
    container_name: service-db-1
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    restart: unless-stopped

